import React, { useState, useRef, useEffect, useCallback, Suspense } from 'react';
import {
    View,
    StyleSheet,
    Alert,
    FlatList,
    TouchableOpacity,
    Vibration,
    Platform,
    PermissionsAndroid,
    KeyboardAvoidingView,
    ScrollView,
} from 'react-native';
import {
    TextInput,
    Button,
    Text,
    Surface,
    IconButton,
    Divider,
    ActivityIndicator,
    Portal,
    Modal,
} from 'react-native-paper';
import { Camera } from 'react-native-camera-kit';
import axios from 'axios';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import { useIsFocused } from '@react-navigation/native';

interface LabelItem {
    id: number;
    item_id: string;
    name: string;
    weight: number;
    mrp: number;
}

interface InwardItem extends LabelItem {
    quantity: number;
}

import { BASE_URL } from '../api/axios';

const StockInwardScreen = () => {
    const isFocused = useIsFocused();
    const [items, setItems] = useState<InwardItem[]>([]);
    const itemsRef = useRef<InwardItem[]>([]);
    const lastScannedCodeRef = useRef<string>('');
    const lastScannedTimeRef = useRef<number>(0);
    const SAME_CODE_COOLDOWN_MS = 1500; // ignore same code re-scan within 1.5s
    const [isScanning, setIsScanning] = useState(false);
    const [manualCode, setManualCode] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [scanMessage, setScanMessage] = useState<{ text: string; type: 'success' | 'error' | 'info' } | null>(null);
    const scanMessageTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

    // Keep ref in sync with state to avoid stale closures in scan callback
    useEffect(() => {
        itemsRef.current = items;
    }, [items]);

    // Show a brief auto-dismissing toast message on the scanner screen
    const showScanMessage = (text: string, type: 'success' | 'error' | 'info' = 'info', duration = 1500) => {
        if (scanMessageTimer.current) clearTimeout(scanMessageTimer.current);
        setScanMessage({ text, type });
        scanMessageTimer.current = setTimeout(() => setScanMessage(null), duration);
    };

    /**
     * Parse raw scanner output and return the clean item_id string,
     * or null if the scanned data doesn't look like a product code.
     *
     * Accepts:
     *   - Plain alphanumeric codes:  "A1B23"
     *   - JSON-like label format:    "{item_id:'A1B23',i:'Name',...}"
     */
    const parseItemCode = (raw: string): string | null => {
        const trimmed = raw.trim();

        // Format 1: JSON-like QR generated by SetLabel screen
        if (trimmed.startsWith('{')) {
            const match = trimmed.match(/item_id:\s*'([^']+)'/);
            if (match && match[1]) return match[1].trim();
            // JSON with double quotes
            const matchDQ = trimmed.match(/"item_id"\s*:\s*"([^"]+)"/);
            if (matchDQ && matchDQ[1]) return matchDQ[1].trim();
            // Could not extract item_id from JSON blob
            return null;
        }

        // Format 2: Plain code — allow letters, digits and hyphens, 3-30 chars
        if (/^[A-Za-z0-9\-]{3,30}$/.test(trimmed)) {
            return trimmed;
        }

        // Anything else (URLs, random text, barcodes unrelated to products) → reject
        return null;
    };

    const requestCameraPermission = async (): Promise<boolean> => {
        if (Platform.OS !== 'android') return true;
        try {
            const granted = await PermissionsAndroid.request(
                PermissionsAndroid.PERMISSIONS.CAMERA,
                {
                    title: 'Camera Permission',
                    message: 'This app needs camera access to scan QR codes.',
                    buttonPositive: 'Allow',
                    buttonNegative: 'Deny',
                }
            );
            if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                return true;
            } else {
                Alert.alert('Permission Denied', 'Camera permission is required to scan QR codes.');
                return false;
            }
        } catch (err) {
            console.warn('Camera permission error:', err);
            return false;
        }
    };

    const fetchAndAddItem = async (itemCode: string) => {
        // itemCode is already parsed & validated by parseItemCode before this is called
        const targetCode = itemCode.trim();

        // Check if already in list using ref (avoids stale closure)
        const currentItems = itemsRef.current;
        const existingIndex = currentItems.findIndex((i) => i.item_id === targetCode);
        if (existingIndex > -1) {
            setItems(prev => {
                const newItems = [...prev];
                newItems[existingIndex] = {
                    ...newItems[existingIndex],
                    quantity: newItems[existingIndex].quantity + 1,
                };
                return newItems;
            });
            Vibration.vibrate(50);
            showScanMessage(`+1 ${currentItems[existingIndex].name}`, 'success', 1000);
            return;
        }

        setIsLoading(true);
        try {
            const response = await axios.get(`${BASE_URL}/api/label/item/detail/${targetCode}/`);
            if (response.data.success) {
                const newItem: InwardItem = {
                    ...response.data.data,
                    quantity: 1,
                };
                setItems(prev => [newItem, ...prev]);
                Vibration.vibrate(100);
                showScanMessage(`✅ Added: ${response.data.data.name}`, 'success');
            } else {
                showScanMessage('⚠️ Item not found in system', 'error');
                Vibration.vibrate([0, 80, 80, 80]); // error pattern
            }
        } catch (error) {
            console.log(error);
            showScanMessage('❌ Network error. Try again.', 'error');
        } finally {
            setIsLoading(false);
        }
    };

    const onReadCode = (event: any) => {
        const rawCode = event?.nativeEvent?.codeStringValue;
        if (!rawCode || rawCode.length === 0) return;

        // Validate: ignore random text / unrelated barcodes in the frame
        const itemCode = parseItemCode(rawCode);
        if (!itemCode) {
            // Not a product code — silently skip, no lock needed
            return;
        }

        const now = Date.now();
        const isSameCode = itemCode === lastScannedCodeRef.current;
        const isWithinCooldown = (now - lastScannedTimeRef.current) < SAME_CODE_COOLDOWN_MS;

        // Only suppress if it's the SAME code scanned again within the cooldown window.
        // A DIFFERENT code is always processed immediately.
        if (isSameCode && isWithinCooldown) {
            return;
        }

        // Record this scan
        lastScannedCodeRef.current = itemCode;
        lastScannedTimeRef.current = now;

        fetchAndAddItem(itemCode);
    };

    const updateQuantity = (itemId: string, delta: number) => {
        setItems((prev) =>
            prev.map((it) => {
                if (it.item_id === itemId) {
                    const newQty = Math.max(1, it.quantity + delta);
                    return { ...it, quantity: newQty };
                }
                return it;
            })
        );
    };

    const removeItem = (itemId: string) => {
        setItems((prev) => prev.filter((it) => it.item_id !== itemId));
    };

    const renderItem = ({ item }: { item: InwardItem }) => (
        <Surface style={styles.itemCard} elevation={2}>
            <View style={styles.itemInfo}>
                <Text style={styles.itemName}>{item.name}</Text>
                <View style={styles.itemSubDetail}>
                    <Text style={styles.itemSubText}>ID: {item.item_id}</Text>
                    <Text style={styles.itemSubText}>  |  </Text>
                    <Text style={styles.itemSubText}>WT: {item.weight}g</Text>
                    <Text style={styles.itemSubText}>  |  </Text>
                    <Text style={styles.itemSubText}>MRP: ₹{item.mrp}</Text>
                </View>
            </View>

            <View style={styles.qtyControls}>
                <IconButton
                    icon="minus-circle-outline"
                    size={24}
                    iconColor="#f44336"
                    onPress={() => updateQuantity(item.item_id, -1)}
                />
                <TextInput
                    value={item.quantity.toString()}
                    onChangeText={(text) => {
                        const val = parseInt(text) || 0;
                        setItems(prev => prev.map(it => it.id === item.id ? { ...it, quantity: val } : it));
                    }}
                    keyboardType="numeric"
                    style={styles.qtyInput}
                    dense
                    mode="flat"
                />
                <IconButton
                    icon="plus-circle-outline"
                    size={24}
                    iconColor="#4caf50"
                    onPress={() => updateQuantity(item.item_id, 1)}
                />
                <IconButton
                    icon="delete-outline"
                    size={22}
                    iconColor="#757575"
                    onPress={() => removeItem(item.item_id)}
                />
            </View>
        </Surface>
    );

    if (isFocused && isScanning) {
        return (
            <View style={styles.scannerContainer}>
                <Camera
                    style={{ flex: 1 }}
                    showFrame={true}
                    scanBarcode={true}
                    onReadCode={onReadCode}
                    frameColor={'white'}
                    laserColor={'red'}
                />
                {isLoading && (
                    <View style={styles.scannerLoadingOverlay}>
                        <ActivityIndicator size="large" color="white" />
                        <Text style={styles.scannerLoadingText}>Looking up item...</Text>
                    </View>
                )}

                {/* Non-blocking toast for scan feedback */}
                {scanMessage && (
                    <View style={[
                        styles.scanToast,
                        scanMessage.type === 'success' && styles.scanToastSuccess,
                        scanMessage.type === 'error' && styles.scanToastError,
                    ]}>
                        <Text style={styles.scanToastText}>{scanMessage.text}</Text>
                    </View>
                )}

                <IconButton
                    icon="close-circle"
                    size={45}
                    iconColor="white"
                    style={styles.closeCamera}
                    onPress={() => setIsScanning(false)}
                />
                <View style={styles.scannerOverlay}>
                    <Text style={styles.scannerText}>Scan Product QR Code</Text>
                    {items.length > 0 && (
                        <Text style={styles.scannerCount}>{items.length} item(s) scanned</Text>
                    )}
                </View>
            </View>
        );
    }

    return (
        <View style={styles.container}>
            <View style={styles.header}>
                <Surface style={styles.searchBar} elevation={4}>
                    <Icon name="barcode-scan" size={24} color="#6200ee" style={{ marginLeft: 10 }} />
                    <TextInput
                        placeholder="Enter Item Code Manually..."
                        value={manualCode}
                        onChangeText={setManualCode}
                        style={styles.input}
                        mode="flat"
                        underlineColor="transparent"
                        activeUnderlineColor="transparent"
                        onSubmitEditing={() => {
                            if (manualCode) {
                                fetchAndAddItem(manualCode);
                                setManualCode('');
                            }
                        }}
                    />
                    {manualCode ? (
                        <IconButton icon="arrow-right-circle" onPress={() => {
                            fetchAndAddItem(manualCode);
                            setManualCode('');
                        }} />
                    ) : null}
                </Surface>

                <Button
                    mode="contained"
                    icon="camera"
                    onPress={async () => {
                        const hasPermission = await requestCameraPermission();
                        if (hasPermission) setIsScanning(true);
                    }}
                    style={styles.scanBtn}
                >
                    Scan QR
                </Button>
            </View>

            {isLoading && <ActivityIndicator style={{ marginVertical: 10 }} />}

            <FlatList
                data={items}
                renderItem={renderItem}
                keyExtractor={(item) => item.item_id}
                contentContainerStyle={styles.listContainer}
                ListEmptyComponent={
                    <View style={styles.emptyState}>
                        <Icon name="package-variant-closed" size={80} color="#ccc" />
                        <Text style={styles.emptyText}>No items added yet</Text>
                        <Text style={styles.emptyHint}>Scan a label or enter code manually</Text>
                    </View>
                }
            />

            {items.length > 0 && (
                <Surface style={styles.footer} elevation={5}>
                    <View style={styles.summary}>
                        <Text style={styles.summaryLabel}>Total Items: <Text style={styles.summaryValue}>{items.length}</Text></Text>
                        <Text style={styles.summaryLabel}>Total Qty: <Text style={styles.summaryValue}>{items.reduce((acc, curr) => acc + curr.quantity, 0)}</Text></Text>
                    </View>
                    <Button mode="contained" onPress={() => Alert.alert('Success', 'Stock Inwarded Successfully')} style={styles.submitBtn}>
                        Submit Inward
                    </Button>
                </Surface>
            )}
        </View>
    );
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8f9fa',
    },
    header: {
        padding: 15,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
        gap: 12,
    },
    searchBar: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        borderRadius: 30,
        borderWidth: 1,
        borderColor: '#e0e0e0',
        overflow: 'hidden',
    },
    input: {
        flex: 1,
        backgroundColor: 'transparent',
        height: 45,
        fontSize: 14,
    },
    scanBtn: {
        borderRadius: 8,
        paddingVertical: 5,
    },
    listContainer: {
        padding: 10,
        paddingBottom: 100,
    },
    itemCard: {
        backgroundColor: '#fff',
        padding: 12,
        borderRadius: 12,
        marginBottom: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    itemInfo: {
        flex: 1,
    },
    itemName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
    },
    itemSubDetail: {
        flexDirection: 'row',
        marginTop: 4,
    },
    itemSubText: {
        fontSize: 11,
        color: '#757575',
    },
    qtyControls: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    qtyInput: {
        width: 45,
        textAlign: 'center',
        backgroundColor: 'transparent',
        height: 35,
        fontSize: 14,
        fontWeight: 'bold',
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 100,
    },
    emptyText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#999',
        marginTop: 20,
    },
    emptyHint: {
        fontSize: 14,
        color: '#aaa',
        marginTop: 5,
    },
    footer: {
        position: 'absolute',
        bottom: 0,
        width: '100%',
        backgroundColor: '#fff',
        padding: 15,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    summary: {
        flex: 1,
    },
    summaryLabel: {
        fontSize: 12,
        color: '#757575',
    },
    summaryValue: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#6200ee',
    },
    submitBtn: {
        borderRadius: 12,
    },
    scannerContainer: {
        flex: 1,
        backgroundColor: 'black',
    },
    scannerOverlay: {
        position: 'absolute',
        top: 100,
        width: '100%',
        alignItems: 'center',
    },
    scannerText: {
        color: 'white',
        fontSize: 18,
        fontWeight: 'bold',
        backgroundColor: 'rgba(0,0,0,0.5)',
        padding: 10,
        borderRadius: 10,
    },
    scannerCount: {
        color: '#4caf50',
        fontSize: 14,
        fontWeight: 'bold',
        backgroundColor: 'rgba(0,0,0,0.5)',
        padding: 6,
        borderRadius: 8,
        marginTop: 8,
    },
    scannerLoadingOverlay: {
        position: 'absolute',
        bottom: 100,
        width: '100%',
        alignItems: 'center',
        gap: 8,
    },
    scannerLoadingText: {
        color: 'white',
        fontSize: 14,
        backgroundColor: 'rgba(0,0,0,0.6)',
        padding: 8,
        borderRadius: 8,
    },
    modalContent: {
        flex: 1,
        backgroundColor: 'black',
    },
    cameraWrapper: {
        flex: 1,
        position: 'relative',
    },
    closeCamera: {
        position: 'absolute',
        top: 40,
        right: 20,
        zIndex: 10,
    },
    scanToast: {
        position: 'absolute',
        bottom: 160,
        alignSelf: 'center',
        backgroundColor: 'rgba(30,30,30,0.92)',
        paddingHorizontal: 22,
        paddingVertical: 12,
        borderRadius: 30,
        maxWidth: '80%',
    },
    scanToastSuccess: {
        backgroundColor: 'rgba(27, 120, 50, 0.92)',
    },
    scanToastError: {
        backgroundColor: 'rgba(180, 30, 30, 0.92)',
    },
    scanToastText: {
        color: 'white',
        fontSize: 15,
        fontWeight: '600',
        textAlign: 'center',
    },
});

export default StockInwardScreen;
